---
- name: Ansible Variable Example Playbook
  hosts: all
  tasks: 

     # display os version
     - debug:
         var: ansible_facts["lsb"]["description"]
           #     msg: current os version is  
     - debug:
         msg: 
           # - ansible lsb fact is {{ ansible_facts.lsb.description }}
           - " {{ ansible_nodename }} ;"
           -  " {{ ansible_os_family }} ; {{ ansible_pkg_mgr }} ; {{ ansible_distribution }} ; {{ ansible_distribution_file_variety }} ; {{ ansible_distribution_version }} "
           -  all ip address list '\n' {{ ansible_all_ipv4_addresses }}